// Static rich content for Bishoy Mesiha's 360° HR profile.
// Will move into profiles_content JSONB once the tabbed admin editor lands.

export interface Stat { value: string; label: string }
export interface Achievement { number: string; desc: string }
export interface Testimonial { text: string; author: string; role?: string; avatar: string }
export interface Metric { val: string; label: string }
export interface Experience { company: string; role: string; period: string; heading: string; bullets: string[] }
export interface Project { title: string; desc: string; result: string }
export interface SpecialtyTestimonial { text: string; author: string }
export interface Specialty {
  id: string; label: string; icon: string; color: string; angle: number;
  tagline: string; summary: string;
  metrics: Metric[]; skills: string[];
  experience: Experience[]; projects: Project[];
  testimonials: SpecialtyTestimonial[];
}

export const HERO = {
  eyebrow: "Dubai, UAE · 16+ Years · 11 MENAT Markets · MBA · PHRi",
  nameFirst: "Bishoy",
  nameLast: "Mesiha",
  tagline: "Not your average HR professional.",
  hook: "Most HR leaders pick a lane. I built a highway.\nFrom AI-powered operating models to sensitive employee crises at 2am — I've done the work that matters, at scale, across 11 countries.",
  stats: [
    { value: "16+", label: "Years Experience" },
    { value: "2K+", label: "Employees Supported" },
    { value: "AED 3M+", label: "Documented Savings" },
    { value: "11", label: "MENAT Countries" },
  ] as Stat[],
};

export const MARQUEE = [
  "🏆 Campaign Middle East — Best Talent Team 2025",
  "✦ Great Place to Work Certified",
  "🎓 MBA · PHRi Certified",
  "🤖 AI-Enabled HR Operating Models",
  "🌍 11 MENAT Markets",
  "📊 Glassdoor 3.0 → 4.1",
];

export const ACHIEVEMENTS: Achievement[] = [
  { number: "30%", desc: "Voluntary turnover reduction through data-driven retention modeling across 3 companies" },
  { number: "AED 3.1M", desc: "Direct cost savings through benefits restructuring and vendor negotiation" },
  { number: "25%", desc: "Strategic HR capacity increased via custom AI agents and automated workflows" },
  { number: "3.0→4.1", desc: "Glassdoor score growth through targeted leaver and engagement initiatives" },
  { number: "96%", desc: "Employee engagement score — up from 76% through culture transformation at scale" },
  { number: "90%", desc: "Payroll complaints eliminated via automation, tightened controls and manager training" },
  { number: "1:80", desc: "HR productivity ratio improved from 1:50 — more output, same headcount" },
  { number: "80%", desc: "Leave accrual liabilities reduced through scheduling compliance and system controls" },
  { number: "100%", desc: "Exit interview completion achieved through redesigned Happy Leavers programme" },
  { number: "50%", desc: "Internship-to-full-time conversion rate via redesigned MCN internship programme" },
];

export const TESTIMONIALS: Testimonial[] = [
  { avatar: "M", author: "Miftahul Ilmi", role: "Executive Virtual Assistant | Facilities & Residence Management", text: "I enjoyed working with Bishoy for little over four years. Not many people can be so efficient. He continuously strived to show <em>the utmost dedication</em> towards his daily tasks. Always calm and open to discussion, extending flexibility towards other departments. <em>I strongly recommend Bishoy as an effective team member and a natural leader.</em>" },
  { avatar: "S", author: "Sherif Al-Sherif", role: "Finance Director MENA, Honeywell | CFO | MBA, University of Manchester | ACCA", text: "Bishoy is one of the greatest among all people I've ever worked with. <em>Powerful, experienced and accountable.</em> Whenever I had a problem, there has never been a time he has left me without a solution. Bishoy will find a way to <em>weather any storm with a smile.</em> He is a really exceptional individual." },
  { avatar: "R", author: "Rosario Olaes", role: "HR Manager | Career Coach | Former Direct Manager", text: "Bishoy is very efficient with his job and has <em>impeccable attention to details.</em> He has always gone beyond his duties to help his colleagues — particularly related to employee relations. He was also <em>instrumental in implementing a new payroll system.</em> Always a pleasure to work with Bishoy." },
  { avatar: "E", author: "Eliane Nader", role: "Cluster Director of People & Culture | Hotelier ME Awards 2024 Nominee", text: "Bishoy is always eager to learn and always adaptable to any changes. He is a <em>fast learner and very professional,</em> great attitude, always willing to assist his team and go the extra mile. <em>Pro-active with strong communication skills.</em> It was a great pleasure working with him." },
  { avatar: "S", author: "Sultan Baddar, SHRM", role: "Director of Human Resources | Former Direct Manager", text: "I can easily say that Bishoy was a professional, hard-working gentleman who always wanted to learn something new. Always open to new ideas, <em>adaptable and a change agent. Computer wizard, a perfect in Excel,</em> and can accomplish tasks ahead of deadline. <em>I would definitely work with him again.</em>" },
];

export const PHILOSOPHY = `"I don't believe HR is a <em>support function</em>.<br>I believe it's the <em>operating system</em> of every great business."`;

export const CONTACT = {
  email: "bmesiha@outlook.com",
  phone: "+971 562 881 713",
  linkedin: "https://www.linkedin.com/in/bmesiha/",
  location: "Dubai, UAE",
};

export const EDUCATION = [
  { degree: "MBA", school: "IBAS, Switzerland (EduQua, ACBSP, IACBE, ATHE Accredited)", year: "2022" },
  { degree: "Bachelor of Commerce (B.Com)", school: "Cairo University — Accounting, Finance, Financial Law & Labour Law", year: "2008" },
  { degree: "PHRi — Professional in Human Resources International", school: "HR Certification Institute", year: "2017" },
  { degree: "UAE & KSA Labour Law Certification", school: "Strategic Axis Training, Dubai", year: "2023" },
  { degree: "Mental Health First Aider", school: "LightHouse Arabia, UAE", year: "2025" },
  { degree: "Young Leaders Blueprint", school: "MCN Leadership Programme", year: "2024" },
];

export const SPECIALTIES: Specialty[] = [
  {
    id: "employee-relations", label: "Employee\nRelations", icon: "⚖️", color: "#c45c2e", angle: 0,
    tagline: "Where Fairness Meets Precision",
    summary: "Complex ER cases resolved with legal accuracy, cultural sensitivity, and business continuity front of mind. From disciplinaries to mass restructuring, across 9 jurisdictions — every scenario navigated well.",
    metrics: [{val:'9',label:'Jurisdictions Covered'},{val:'100%',label:'Compliance Rate'},{val:'0',label:'Legal Escalations'},{val:'600+',label:'Employees Covered'},{val:'50+',label:'Managers ER Trained'},{val:'80%',label:'Escalation Reduction'}],
    skills: ['Complex ER Case Management','Multi-Jurisdiction Investigations','Disciplinary & Grievance Processes','PIPs & PDPs','Duty-of-Care Crisis Management','Mass Restructuring Consultation','Sensitive Welfare Cases','UAE & GCC Labour Law','KSA / Egypt Labour Law','MOHRE Compliance','Manager ER Coaching','ER Framework Design'],
    experience: [
      {company:'MCN / Omnicom',role:'Regional Senior BP, People & Talent (Assoc. Director)',period:'Jul 2024–Present',heading:'ER Governance Across 11 MENAT Markets',bullets:['Lead employee relations across 2,000+ employees in 11 countries, coaching agency CEOs and MDs through complex and sensitive situations','Establish consistent ER governance frameworks across diverse legal jurisdictions — UAE freezone/mainland, KSA, Qatar, Kuwait, Bahrain, Jordan, Egypt','Mentor and upskill HR managers on ER best practices and difficult conversations, embedding fair and legally sound processes','Handle escalated ER cases requiring duty-of-care interventions, mental health considerations, and C-suite stakeholder management']},
      {company:'Hill & Knowlton / Burson (WPP)',role:'Senior HR Manager, META',period:'Nov 2022–Jul 2024',heading:'Post-Merger ER Harmonisation at Scale',bullets:['Led co-worker consultation during merger restructuring of 600+ employees across 10 offices with empathy, legal precision, and full regulatory compliance','Harmonised disciplinary and grievance frameworks across two merged entities with different legal heritage and policy cultures','Delivered ER training for line managers across META, building frontline capability to handle issues before escalation','Zero legal claims or employment tribunal proceedings during a period of significant organisational change']},
      {company:'APCO Worldwide',role:'Senior HR Business Partner, MENA',period:'Apr 2019–Nov 2022',heading:'Building ER Infrastructure from Scratch',bullets:['Built ER policies and grievance mechanisms for 300+ employee MENA operation with no prior formal ER framework','Handled the full spectrum of ER cases — disciplinaries, grievances, performance concerns, interpersonal conflicts — across UAE, KSA, and broader MENA','Partnered with legal on complex cross-border employee matters requiring multi-jurisdiction expertise']},
      {company:'Minor Hotels Group',role:'Asst. HR Manager / HR & Training Manager / HR Supervisor',period:'Feb 2014–Jan 2019',heading:'High-Volume ER in Luxury Hospitality',bullets:['Managed employee relations for 1,300+ employees across three UAE 5-star hotels — a high-pressure, multicultural frontline environment','Handled disciplinary cases, grievances, and sensitive personal situations with procedural accuracy and genuine care','Managed MOHRE filings, visa processes, and employment contract governance with full compliance']},
      {company:'Development & Housing Company',role:'HR Administrator & Accountant',period:'Jan 2010–Feb 2014',heading:'Early ER & Compliance Foundation',bullets:['Managed HR operations and compliance for 350 employees across seven projects in Cairo','Ensured compliance with Egyptian labour law and social insurance regulations','Managed employee documentation, onboarding, offboarding, and administration']},
    ],
    projects: [{title:'ER Governance Framework Design',desc:'Built ER policy infrastructure across 11 jurisdictions with clear escalation paths, investigation standards, and manager accountability.',result:'Zero legal escalations across MENAT region'},{title:'Restructuring Consultation Programme',desc:'Designed and led sensitive co-worker consultation during post-merger restructuring — balancing commercial necessity with human dignity.',result:'Full regulatory compliance, no employment claims'},{title:'Manager ER Capability Programme',desc:'Created and delivered ER training curriculum for 50+ line managers covering difficult conversations, PIPs, and grievance handling.',result:'80% reduction in HR escalations within 6 months'}],
    testimonials: [{text:'"Whenever I had a problem, there has never been a time he has left me without a solution. Bishoy will find a way to weather any storm with a smile."',author:'Sherif Al-Sherif, Finance Director MENA, Honeywell'},{text:'"Bishoy has always gone beyond his duties and responsibilities just to help his colleagues particularly related to employee relations."',author:'Rosario Olaes, HR Manager (Former Direct Manager)'}],
  },
  {
    id: "total-rewards", label: "Total\nRewards", icon: "💎", color: "#2d6a4f", angle: 45,
    tagline: "Compensation That Competes & Retains",
    summary: "Designing reward frameworks that attract top talent, retain critical performers, and deliver measurable ROI — from executive packages to frontline incentive schemes, across 9 jurisdictions.",
    metrics: [{val:'AED 3.1M',label:'Direct Cost Savings'},{val:'12%',label:'YoY Benefits Reduction'},{val:'30%',label:'Vendor Cost Cut'},{val:'9',label:'Jurisdictions'},{val:'2K+',label:'Employees in Scope'},{val:'2%',label:'Budget Forecast Variance'}],
    skills: ['Compensation Framework Design','Salary Grid & Banding','Executive Package Preparation','Market Benchmarking','Bonus & Incentive Scheme Design','Annual Merit Review','Variable Pay Structures','Benefits Policy & Administration','Pay Equity Analysis','Total Rewards Strategy','HR Budget Ownership','Power BI Rewards Analytics'],
    experience: [
      {company:'MCN / Omnicom',role:'Regional Senior BP, People & Talent (Assoc. Director)',period:'Jul 2024–Present',heading:'Total Rewards Architecture for 2,000+ MENAT Employees',bullets:['Partner with global C&B CoE on market benchmarking, salary reviews, and annual compensation cycles across 11 markets','Design and maintain skills-based career ladders and job architecture underpinning structured compensation reviews','Manage benefits programmes and provider relationships, driving competitive design and cost discipline simultaneously','Lead variable pay and incentive structure design aligning performance-related pay with commercial outcomes','Build Power BI reward analytics dashboards enabling EXCOM-level compensation decisions with full data visibility']},
      {company:'Hill & Knowlton / Burson (WPP)',role:'Senior HR Manager, META',period:'Nov 2022–Jul 2024',heading:'Post-Merger Total Rewards Harmonisation',bullets:['Achieved AED 1.1M in cost savings through disciplined benefits restructuring and vendor management with full ROI reporting','Led compensation harmonisation across merged entities — unified salary grids and benefits frameworks for the combined organisation','Built integrated People Intelligence dashboards linking compensation cost, attrition, and engagement data']},
      {company:'APCO Worldwide',role:'Senior HR Business Partner, MENA',period:'Apr 2019–Nov 2022',heading:'Data-Driven Rewards Optimisation',bullets:['Delivered 12% YoY benefits cost reduction across housing and medical plans through vendor optimisation and contract renegotiation','Achieved AED 2.0M in direct cost savings through disciplined spend management and vendor negotiation','Partnered with finance to forecast HR budget, achieving variance within 2% annually']},
      {company:'Minor Hotels Group',role:'HR Manager & Supervisor',period:'Feb 2014–Jan 2019',heading:'Variable Pay in a Revenue-Driven Environment',bullets:['Supported incentive schemes for Front Office and Reservations teams, aligning performance with revenue and upselling targets','Contributed to variable pay structures for revenue-generating roles, linking KPIs to incentive payouts','Reduced payroll complaints by 90% via automation and tightened controls','Reduced leave accrual liabilities by 80% through improved scheduling compliance']},
      {company:'Development & Housing Company',role:'HR Administrator & Accountant',period:'Jan 2010–Feb 2014',heading:'Payroll & Compensation Administration',bullets:['Managed payroll and HR operations for 350 employees across seven projects, combining HR with full accountancy responsibilities','Built financial acumen applied throughout career — deep understanding of cost structures and budget management']},
    ],
    projects: [{title:'Regional Compensation Harmonisation',desc:'Post-merger salary grid unification across 10 offices and 2 legal entities with different pay scales and benefit entitlements.',result:'AED 1.1M savings + no pay equity complaints'},{title:'Benefits Vendor Renegotiation',desc:'Full audit of insurance and benefits providers across MENAT; competitive tender and renegotiation delivering sustained cost reductions.',result:'30% reduction in vendor costs'},{title:'People Intelligence Rewards Dashboard',desc:'Built Power BI reward analytics module tracking compensation costs, merit spend, and pay band distribution in real time.',result:'EXCOM compensation decisions made in minutes'}],
    testimonials: [{text:'"Bishoy is one of the greatest among all people I\'ve ever worked with. Powerful, experienced and accountable — responsible for many countries in the MENA region."',author:'Sherif Al-Sherif, Finance Director MENA, Honeywell'}],
  },
  {
    id: "hr-digital-transformation", label: "HR Digital\nTransform.", icon: "🤖", color: "#1a3a5c", angle: 90,
    tagline: "The Human Side of the Machine",
    summary: "Building AI-enabled HR operating models before it was fashionable. Automating what slows people down so HR can do what machines can't — think, connect, and lead.",
    metrics: [{val:'25–30%',label:'HR Capacity Gained'},{val:'4+',label:'Processes Automated'},{val:'30%',label:'Efficiency Increase'},{val:'3',label:'HRIS Implementations'},{val:'100%',label:'Exit Interview Rate'},{val:'60%',label:'Onboarding Time Saved'}],
    skills: ['Custom AI Agent Development','AI-Powered HR Workflows','Intelligent Onboarding Automation','Predictive Attrition Modeling','Prompt Engineering for HR','End-to-End HR Process Automation','HRIS Implementation (Workday, SAP SF, Oracle HCM, Taleo)','Power BI People Dashboards','Digital Governance Design','HR Tech Stack Assessment','Digital Offboarding Design'],
    experience: [
      {company:'MCN / Omnicom',role:'Regional Senior BP, People & Talent (Assoc. Director)',period:'Jul 2024–Present',heading:'AI-Enabled HR Operating Model at Scale',bullets:['Designed AI-supported HR operating models automating core workflows, increasing strategic HR capacity by 25–30% across 2,000+ employees','Built integrated People Intelligence dashboards in Power BI linking attrition, engagement, compensation cost, and headcount for EXCOM decisions','Developed custom AI agents reducing administrative effort and freeing strategic capacity within the HR team','Applied automation across onboarding, offboarding, compliance, reporting, and analytics across 11 jurisdictions']},
      {company:'Hill & Knowlton / Burson (WPP)',role:'Senior HR Manager, META',period:'Nov 2022–Jul 2024',heading:'Digital Transformation Through Merger',bullets:['Designed HR digital solutions increasing operational efficiency by 30%, creating capacity for higher-value strategic work','Led HRIS integration and data harmonisation across merged entities, ensuring data integrity and compliance reporting accuracy','Revamped offboarding digitally, increasing exit-interview completion to 100% and generating 20+ actionable workforce insights per cycle']},
      {company:'APCO Worldwide',role:'Senior HR Business Partner, MENA',period:'Apr 2019–Nov 2022',heading:'HR Intelligence Architecture',bullets:['Built HR intelligence dashboards automating routine reporting and providing real-time workforce visibility','Streamlined offboarding processes digitally, cutting cycle time by 50% and improving compliance to 100%','Improved Glassdoor score from 3.0 to 4.1 through data-driven leaver analysis and targeted interventions']},
      {company:'Minor Hotels Group',role:'HR Manager & Supervisor',period:'Feb 2014–Jan 2019',heading:'HR Digitisation in High-Volume Operations',bullets:['Reduced payroll complaints by 90% through automation, tightened controls, and digital payroll tools','Cut HR costs by 20% via digitisation and vendor renegotiation','Introduced onboarding digital tools reducing process time by 60%','Instituted HRIS modules and reduced leave-accrual costs by 80%']},
      {company:'Development & Housing Company',role:'HR Administrator & Accountant',period:'Jan 2010–Feb 2014',heading:'Early Systems & Process Foundation',bullets:['Introduced onboarding tools reducing process time by 60% across seven project sites','Combined HR administration with accountancy — building early understanding of system integration and data accuracy']},
    ],
    projects: [{title:'Custom AI Agent Suite',desc:'Developed multiple custom AI agents automating HR document generation, policy Q&A, onboarding journeys, and compliance tracking.',result:'+25% strategic HR capacity released'},{title:'HRIS Multi-Implementation Lead',desc:'Directed regional implementation of Workday, SAP SuccessFactors, and Oracle HCM across multiple organisations.',result:'3 HRIS systems successfully deployed'},{title:'People Intelligence Dashboard',desc:'Designed and built integrated Power BI dashboards connecting attrition, engagement, headcount, and compensation data.',result:'Real-time workforce visibility for EXCOM'}],
    testimonials: [{text:'"Computer wizard, perfect in Excel, and can accomplish tasks ahead of deadline."',author:'Sultan Baddar SHRM, Director of HR (Former Direct Manager)'}],
  },
  {
    id: "hr-compliance", label: "HR\nCompliance", icon: "🛡️", color: "#4a1a5c", angle: 135,
    tagline: "Zero Gaps. Zero Surprises.",
    summary: "Multi-jurisdiction compliance is business protection. I've built governance frameworks across 9 countries, navigated complex immigration cases, and maintained full regulatory adherence through mergers, restructurings, and rapid growth.",
    metrics: [{val:'9',label:'Jurisdictions Covered'},{val:'100%',label:'Audit Readiness'},{val:'3',label:'Handbooks Authored'},{val:'11',label:'MENAT Markets Governed'},{val:'0',label:'Regulatory Incidents'},{val:'100%',label:'Nationalisation On-Time'}],
    skills: ['UAE Mainland & Freezone Labour Law','KSA Labour Law','Qatar, Kuwait, Bahrain, Jordan, Egypt','MOHRE & Government Compliance','Emiratisation & Saudization Strategy','Visa & Immigration Governance','Policy Harmonisation','Multi-Jurisdiction Audit Readiness','Employee Handbook Design','Regulatory Risk Mitigation','UAE & KSA Labour Law Certified (2023)'],
    experience: [
      {company:'MCN / Omnicom',role:'Regional Senior BP, People & Talent (Assoc. Director)',period:'Jul 2024–Present',heading:'Regional Compliance Governance Across 11 Markets',bullets:['Established internal HR audit and data-integrity mechanisms across 11 jurisdictions, ensuring zero compliance gaps','Integrated digital governance structures ensuring multi-jurisdiction regulatory adherence','Managed regional mobility compliance and visa/immigration governance for senior hires and transfers','Built Emiratisation and Saudization pipelines with structured Management Trainee programmes meeting nationalisation targets']},
      {company:'Hill & Knowlton / Burson (WPP)',role:'Senior HR Manager, META',period:'Nov 2022–Jul 2024',heading:'Policy Harmonisation Through Complex Merger',bullets:['Authored comprehensive employee handbook and regional policy framework for merged entities across 10 offices','Maintained full MOHRE and regulatory compliance throughout post-merger restructuring processes','Launched Emiratisation and Saudization programmes meeting nationalisation targets on schedule','Collaborated with legal on complex cross-border employment matters and regulatory risk mitigation']},
      {company:'APCO Worldwide',role:'Senior HR Business Partner, MENA',period:'Apr 2019–Nov 2022',heading:'Compliance Architecture for MENA Expansion',bullets:['Implemented internal HR audit mechanisms and data-integrity activities across all operating countries','Collaborated with legal on labour law matters across UAE, KSA, Qatar, Bahrain, Jordan, and Egypt','Ensured full compliance throughout regional growth with zero regulatory incidents']},
      {company:'Minor Hotels Group',role:'HR Manager & Supervisor',period:'Feb 2014–Jan 2019',heading:'High-Volume Immigration & Labour Compliance',bullets:['Managed all UAE visa, immigration, and MOHRE compliance for 1,300+ diverse expatriate employees across three properties','Oversaw new hire processing, renewals, and cancellations with zero compliance incidents','Managed full employment lifecycle compliance including disciplinary and contract governance']},
      {company:'Development & Housing Company',role:'HR Administrator & Accountant',period:'Jan 2010–Feb 2014',heading:'Egyptian Labour Law & Compliance Foundation',bullets:['Ensured compliance with Egyptian labour law and social insurance across seven projects and 350 employees','Managed HR documentation, contracts, and government filings with precision']},
    ],
    projects: [{title:'Regional Policy Harmonisation Framework',desc:'Authored 3 employee handbooks and a unified regional policy framework following high-complexity merger of two global consultancies.',result:'Zero policy ambiguity across 10 offices'},{title:'Emiratisation & Saudization Pipeline',desc:'Built structured nationalisation pipelines including Management Trainee programmes meeting regulatory targets.',result:'Nationalisation targets met every cycle'},{title:'Multi-Jurisdiction Compliance Audit',desc:'Designed and executed HR audit framework across 11 MENAT jurisdictions, remediating risks before regulatory exposure.',result:'100% audit readiness across all markets'}],
    testimonials: [{text:'"He is a organized and customer-service oriented perfectionist, has no problem to work hard when necessary."',author:'Sherif Al-Sherif, Finance Director MENA, Honeywell'}],
  },
  {
    id: "learning-development", label: "Learning\n& Dev.", icon: "🎓", color: "#5c3d1a", angle: 180,
    tagline: "Capability That Sticks",
    summary: "L&D isn't a training calendar — it's a business transformation tool. I design annual learning strategies, TNA frameworks, and leadership development programmes that build real capability and deliver measurable performance results.",
    metrics: [{val:'25%',label:'New-Hire Retention Uplift'},{val:'50%',label:'Internship-to-Hire Rate'},{val:'1,300+',label:'Employees L&D Coverage'},{val:'11',label:'Markets Reached'},{val:'96%',label:'Engagement via Culture L&D'},{val:'80%',label:'Manager Escalation Reduction'}],
    skills: ['Annual L&D Strategy Design','Training Needs Analysis (TNA)','Leadership Development Programmes','Competency Framework Design','Career Ladder Architecture','Individual Development Plans (IDPs)','Learning Measurement & ROI','Digital & AI-Enabled Learning','Manager Development','Facilitation (Arabic & English)','LinkedIn Learning','SAP SuccessFactors LMS'],
    experience: [
      {company:'MCN / Omnicom',role:'Regional Senior BP, People & Talent (Assoc. Director)',period:'Jul 2024–Present',heading:'Regional L&D Strategy Across Communications Network',bullets:['Design and coordinate comprehensive L&D curriculum from TNA to execution across 11 MENAT markets','Designed regional onboarding programme improving new-hire experience and retention by 25%','Built structured career ladders and job architecture across multiple agencies giving employees clear growth pathways','Developed MCN internship programme improving internship-to-full-time conversion to 50%','Delivered career-readiness sessions at De Montfort University as part of MCN CSR activities']},
      {company:'Hill & Knowlton / Burson (WPP)',role:'Senior HR Manager, META',period:'Nov 2022–Jul 2024',heading:'Capability Building Through Transformation',bullets:['Led HRIS and talent management training for HR and manager communities during digital transformation rollout','Designed manager development initiatives increasing ER capability and reducing HR escalations','Built succession and IDP frameworks for critical roles across META offices']},
      {company:'APCO Worldwide',role:'Senior HR Business Partner, MENA',period:'Apr 2019–Nov 2022',heading:'L&D as Engagement Driver',bullets:['Led career development and succession planning strategies reducing voluntary turnover by 30%','Drove cultural initiatives improving engagement survey scores by 5% YoY with L&D as a primary lever','Designed and delivered manager programmes on performance conversations, ER handling, and team effectiveness']},
      {company:'Minor Hotels Group',role:'Assistant HR & Training Manager / HR Supervisor',period:'Feb 2014–Jan 2019',heading:'L&D at the Heart of Hospitality Excellence',bullets:['Managed full L&D planning, training delivery, and compliance for 1,300+ employees across three 5-star hotel properties','Led cultural transformation driving engagement from 76% to 96% — with L&D as a primary culture-change mechanism','Increased HR productivity ratio from 1:50 to 1:80 through training, upskilling, and process efficiency programmes']},
      {company:'Development & Housing Company',role:'HR Administrator & Accountant',period:'Jan 2010–Feb 2014',heading:'Onboarding & Training Foundation',bullets:['Introduced onboarding tools reducing process time by 60% across multiple project sites','Built early foundation in process design, documentation, and training delivery']},
    ],
    projects: [{title:'Regional Onboarding Transformation',desc:'Redesigned onboarding across 11 markets — structured, culturally sensitive, accelerating time-to-productivity.',result:'+25% new-hire retention in first 6 months'},{title:'Career Ladder Architecture',desc:'Designed skills-based career ladders and job architecture across multiple agencies, clarifying progression and informing development planning.',result:'Reduced "no growth" attrition by 30%'},{title:'Manager Development Programme',desc:'Built and delivered manager capability programme covering ER, performance conversations, inclusive leadership, and commercial HR thinking.',result:'50+ managers upskilled; 80% reduction in escalations'}],
    testimonials: [{text:'"He is a fast learner and very professional, great attitude, always willing to assist his team and go the extra mile. Pro-active and strong communication skills."',author:'Eliane Nader, Cluster Director of People & Culture'}],
  },
  {
    id: "hr-strategy", label: "HR\nStrategy", icon: "🧭", color: "#1a4a4a", angle: 225,
    tagline: "People Strategy as Business Strategy",
    summary: "Trusted advisor to CEOs and EXCOM teams — translating business ambitions into people operating models that deliver. From workforce architecture to Employer Branding and EVP, I own the full strategic People agenda.",
    metrics: [{val:'2,000+',label:'Employees Strategically Led'},{val:'11',label:'MENAT Markets'},{val:'2%',label:'Budget Forecast Variance'},{val:'3',label:'Post-Merger Integrations'},{val:'AED 3.1M',label:'Savings Delivered'},{val:'3.0→4.1',label:'Glassdoor Growth'}],
    skills: ['People & Culture Strategy Design','Annual People Plan Ownership','CEO & EXCOM Advisory','Commercial HR Advisory','Business Transformation Leadership','M&A People Due Diligence','Post-Merger Integration','Workforce Planning & Headcount Budgets','Succession Architecture','Employer Branding & EVP Strategy','Greenfield Market Launch','Power BI Strategic Dashboards'],
    experience: [
      {company:'MCN / Omnicom',role:'Regional Senior BP, People & Talent (Assoc. Director)',period:'Jul 2024–Present',heading:'EXCOM-Level People Strategy Across MENAT',bullets:['Act as strategic workforce advisor to agency CEOs, aligning talent architecture, cost models, and succession pipelines with growth strategy','Own regional HR budget and manpower planning, providing variance analysis, workforce cost tracking, and data-informed EXCOM recommendations','Lead workforce architecture including skills-based design, career frameworks, and succession planning for critical roles','Design and execute regional people plan translating Omnicom global strategy into locally relevant HR programmes','Champion Employer Branding and EVP across the MCN network — including Campaign ME Best Talent Team 2025 win and Great Place to Work certifications']},
      {company:'Hill & Knowlton / Burson (WPP)',role:'Senior HR Manager, META',period:'Nov 2022–Jul 2024',heading:'Strategic HR Lead Through Post-Merger Integration',bullets:['Set and drove the People agenda through merger integration, owning policy harmonisation, talent frameworks, performance management, and compliance across 600+ employees','Partnered with WPP global People & Culture CoEs translating global frameworks into locally relevant people practices','Launched Happy Leavers offboarding programme — an EVP-enhancing initiative turning leavers into brand advocates','Developed HR strategies, budgeting, and forecasting aligned with organisational goals through a period of significant change']},
      {company:'APCO Worldwide',role:'Senior HR Business Partner, MENA',period:'Apr 2019–Nov 2022',heading:'Building MENA People Strategy from Blueprint',bullets:['Partnered with Regional HR Director on HR strategy, forecasting, and talent development for 300+ MENA employees','Partnered with finance to forecast HR budget, achieving variance within 2% annually','Improved Glassdoor employer brand score from 3.0 to 4.1 through targeted EVP and leaver experience initiatives','Drove D&I strategy across 11 countries, navigating diverse cultural norms while advancing meritocracy and inclusion']},
      {company:'Minor Hotels Group',role:'HR Manager & Supervisor',period:'Feb 2014–Jan 2019',heading:'HR Strategy in Large-Scale Hospitality',bullets:['Managed workforce planning, budgeting, and HR strategy across 1,300+ employees at three 5-star UAE hotels','Led manning budgets, L&D planning, restructuring, and compliance — full HR operating ownership at scale','Increased HR productivity ratio from 1:50 to 1:80 — strategic resource allocation without headcount addition']},
      {company:'Development & Housing Company',role:'HR Administrator & Accountant',period:'Jan 2010–Feb 2014',heading:'Early HR Strategy & Planning Foundation',bullets:['Managed HR strategy and workforce administration for 350 employees across seven projects','Combined HR with accountancy, building foundational understanding of cost management and business planning']},
    ],
    projects: [{title:'MENAT People Operating Model',desc:'Architected the full people operating model for a 2,000+ employee MENAT network: governance, HRBP model, talent architecture, and digital enablement.',result:'Adopted by EXCOM as regional standard'},{title:'Employer Brand & EVP Strategy',desc:'Drove employer brand elevation across MENAT including Best Talent Team 2025, Great Place to Work certifications, Glassdoor 3.0→4.1, and the Happy Leavers programme.',result:'Industry award + measurable brand improvement'},{title:'Post-Merger People Integration',desc:'Led full HR integration through 3 post-merger scenarios, harmonising culture, policies, pay, and systems.',result:'Zero culture-related attrition during integration'}],
    testimonials: [{text:'"Bishoy is one of the greatest among all people I\'ve ever worked with. Powerful, experienced and accountable HR Advisor responsible for many countries in the MENA region."',author:'Sherif Al-Sherif, Finance Director MENA, Honeywell'}],
  },
  {
    id: "od-change-management", label: "OD &\nChange", icon: "🔄", color: "#5c1a2e", angle: 270,
    tagline: "Change People Can Actually Follow",
    summary: "Organisational design and change management done right: with clear communication, genuine empathy, and enough rigour to make it stick. I've redesigned organisations, launched markets, and guided 600-person integrations without losing the human thread.",
    metrics: [{val:'+12%',label:'Engagement During Change'},{val:'600+',label:'Employees Through Integration'},{val:'10',label:'Offices Integrated'},{val:'76→96%',label:'Engagement Journey'},{val:'5%',label:'Annual Engagement Uplift'},{val:'3',label:'Merger Integrations Led'}],
    skills: ['Organisational Design & Restructuring','Change Management Strategy','Culture Transformation','Post-Merger Integration Planning','Greenfield Market Launch','D&I Strategy Design','Employee Experience Journey Mapping','Engagement Survey Design & Action Planning','Wellbeing Programme Design','Internal Communications Strategy','Culture Committee Leadership'],
    experience: [
      {company:'MCN / Omnicom',role:'Regional Senior BP, People & Talent (Assoc. Director)',period:'Jul 2024–Present',heading:'Culture & OD Stewardship Across MENAT',bullets:['Form and support the Corporate Employee Culture Committee, delivering targeted engagement initiatives and wellbeing programmes','Lead organisational design work across agencies, including restructuring, role clarification, and capability mapping','Drive D&I awareness and inclusion initiatives across 11 countries, navigating diverse cultural norms','Design employee experience programmes that improve engagement and strengthen employer brand']},
      {company:'Hill & Knowlton / Burson (WPP)',role:'Senior HR Manager, META',period:'Nov 2022–Jul 2024',heading:'Leading Change During Complex Merger',bullets:['Directed cultural and structural integration of 600+ employees across 10 offices through a major post-merger scenario','Contributed to +12% regional engagement uplift through targeted culture, wellbeing, and internal communications programmes','Led co-worker consultation and communication processes during restructuring with empathy and legal precision','Launched Happy Leavers offboarding programme increasing exit-interview completion to 100% and generating retention insights']},
      {company:'APCO Worldwide',role:'Senior HR Business Partner, MENA',period:'Apr 2019–Nov 2022',heading:'Engagement & Culture as Strategic Levers',bullets:['Drove cultural initiatives improving engagement survey scores by 5% on average YoY through structured listening and action planning','Improved Glassdoor score from 3.0 to 4.1 through targeted leaver and brand initiatives','Led D&I initiatives across 11 markets navigating diverse cultural contexts']},
      {company:'Minor Hotels Group',role:'HR Manager & Supervisor',period:'Feb 2014–Jan 2019',heading:'Culture Transformation at Scale in Hospitality',bullets:['Led cultural transformation driving engagement from 76% to 96% across 1,300+ employees at three 5-star hotels','Managed wellness programmes for 1,300+ staff reducing absenteeism and improving employer brand','Built a high-performance culture grounded in accountability, recognition, and meritocracy in a diverse frontline environment']},
      {company:'Development & Housing Company',role:'HR Administrator & Accountant',period:'Jan 2010–Feb 2014',heading:'Change Management & Onboarding',bullets:['Introduced onboarding tools reducing process time by 60% — an early change management initiative improving employee experience','Managed transitions across seven project sites, maintaining operational continuity through staff changes']},
    ],
    projects: [{title:'Post-Merger Cultural Integration',desc:'Designed and executed cultural integration for 600-person merged entity across 10 offices: values alignment, communication strategy, and leadership narrative.',result:'+12% engagement during integration period'},{title:'Corporate Culture Committee',desc:'Founded and facilitated employee-led Culture Committee driving grassroots engagement, wellbeing, and DEI initiatives across MENAT network.',result:'Great Place to Work certification across multiple markets'},{title:'Engagement Score Transformation',desc:'Drove systematic engagement improvement from 76% to 96% through structured listening, cultural programming, and manager accountability frameworks.',result:'96% engagement — industry-leading for the sector'}],
    testimonials: [{text:'"He is always eager to learn and always adaptable to any changes. A fast learner and very professional, great attitude, always willing to assist his team and go the extra mile."',author:'Eliane Nader, Cluster Director of People & Culture'}],
  },
  {
    id: "hr-consultancy", label: "HR\nConsultancy", icon: "🎯", color: "#5a4010", angle: 315,
    tagline: "Fractional Expertise. Full-Time Impact.",
    summary: "Advisory and consultancy services for organisations that need senior HR thinking — from strategy design to AI transformation, Employer Branding, and EVP design. A practitioner's precision with a consultant's perspective.",
    metrics: [{val:'10+',label:'Advisory Disciplines'},{val:'9',label:'Jurisdictions Expertise'},{val:'16+',label:'Years Practitioner'},{val:'AED 3.1M',label:'Value Delivered'},{val:'MENAT',label:'Regional Reach'},{val:'3',label:'HRIS Implementations'}],
    skills: ['HR Strategy Consulting','Organisational Design Advisory','Job Architecture & Grading','Compensation Benchmarking','Employee Handbook Design','HR Policy Frameworks','Talent Management Framework Design','L&D Strategy & Curriculum Design','Culture & Engagement Diagnostics','M&A People Due Diligence','AI-Enabled Workflow Design','ER Advisory & Investigation Frameworks','Employer Branding & EVP Advisory','HRIS Selection & Optimisation'],
    experience: [
      {company:'MCN / Omnicom',role:'Acting as Internal Strategic Consultant',period:'Jul 2024–Present',heading:'Strategic HR Consulting to Agency CEOs',bullets:['Deliver consulting-grade people strategy advisory to multiple agency CEOs across different industries within MCN network','Design and advise on workforce architecture, succession planning, and talent management frameworks across diverse business units','Provide M&A people advisory including due diligence support and integration planning for acquired agencies','Drive Employer Branding and EVP strategy across the network — contributing to Campaign ME Best Talent Team 2025 and Great Place to Work wins']},
      {company:'Hill & Knowlton / Burson (WPP)',role:'Senior HR Manager, META',period:'Nov 2022–Jul 2024',heading:'Post-Merger HR Transformation Advisory',bullets:['Primary people strategy advisor through complex post-merger integration of two global PR consultancies','Designed compensation harmonisation, policy frameworks, and talent architecture for the combined entity','Delivered AED 1.1M in advisory-driven cost savings through benefits restructuring and vendor management']},
      {company:'APCO Worldwide',role:'Senior HR Business Partner, MENA',period:'Apr 2019–Nov 2022',heading:'MENA HR Strategy & Advisory',bullets:['Provided strategic HR advisory to Regional HR Director and executive leadership on workforce design and investment decisions','Built HR governance, compliance, and operating model for 300+ employee MENA operation from scratch','Delivered sustained 12% YoY benefits cost reduction through disciplined advisory on vendor and benefits management']},
      {company:'Minor Hotels Group',role:'HR Manager & Supervisor',period:'Feb 2014–Jan 2019',heading:'Operational HR Consulting in Hospitality',bullets:['Managed full HR consulting and operations for 1,300+ employee hospitality environment across three properties','Advised property GMs on people strategy, workforce planning, performance, and ER — trusted HR business partner','Delivered 20% cost savings through digitisation and vendor renegotiation advisory']},
      {company:'Development & Housing Company',role:'HR Administrator & Accountant',period:'Jan 2010–Feb 2014',heading:'Early Advisory Foundation',bullets:['Advised seven project teams on HR and payroll operations, acting as the internal HR and finance advisor for all sites']},
    ],
    projects: [{title:'Full HR Strategy Design',desc:'End-to-end people strategy design for organisations at inflection points: scaling, restructuring, launching new markets, or post-acquisition.',result:'Delivered across 5+ organisations as strategic advisor'},{title:'Employer Branding & EVP Build',desc:'Design and execution of employer value proposition, candidate experience, and employer brand narrative — from GPTW certification to Glassdoor improvement.',result:'Best Talent Team 2025 + Glassdoor 3.0→4.1'},{title:'AI-Enabled HR Transformation',desc:'Advisory on AI workflow design, HRIS selection, and digital HR operating model for organisations ready to automate and elevate their HR function.',result:'25%+ capacity gains for HR teams'}],
    testimonials: [{text:'"Bishoy continuously strived his ladder up by showing the utmost dedication towards his daily tasks, willing to enhance his knowledge till pursuing his passion in Human Resources."',author:'Miftahul Ilmi, Executive Virtual Assistant (Former Colleague)'}],
  },
];
