import { corsHeaders } from "https://esm.sh/@supabase/supabase-js@2.95.0/cors";

const GATEWAY_URL = "https://connector-gateway.lovable.dev/resend";

// Sender. Falls back to Resend's shared sandbox address if no verified domain
// is configured via the RESEND_FROM_EMAIL secret.
const FROM_NAME = "Bishoy @ People.Studio";
const DEFAULT_FROM_EMAIL = "onboarding@resend.dev";
const BOOKING_LINK = "https://wa.me/971581784948";

interface RequestBody {
  toEmail: string;
  documentKind: "Policy" | "Job Description" | string;
  documentName: string;
  outputText: string;
}

function escapeHtml(s: string) {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function renderHtml(documentKind: string, documentName: string, outputText: string) {
  // Convert the plain-text output (uses "## Heading" markers) into simple HTML.
  const blocks = outputText.split(/\n{2,}/).map((block) => {
    const lines = block.split("\n");
    const headingMatch = lines[0]?.match(/^##\s+(.*)$/);
    if (headingMatch) {
      const heading = escapeHtml(headingMatch[1]);
      const bodyLines = lines.slice(1);
      const bullets = bodyLines.every((l) => /^\s*[-*]\s+/.test(l)) && bodyLines.length > 0;
      if (bullets) {
        const items = bodyLines
          .map((l) => `<li style="margin:0 0 6px;">${escapeHtml(l.replace(/^\s*[-*]\s+/, ""))}</li>`)
          .join("");
        return `<h3 style="font-size:15px;margin:22px 0 8px;color:#1a1a1a;">${heading}</h3><ul style="padding-left:18px;margin:0 0 12px;color:#333;font-size:14px;line-height:1.6;">${items}</ul>`;
      }
      return `<h3 style="font-size:15px;margin:22px 0 8px;color:#1a1a1a;">${heading}</h3><p style="margin:0 0 12px;color:#333;font-size:14px;line-height:1.6;white-space:pre-wrap;">${escapeHtml(bodyLines.join("\n"))}</p>`;
    }
    return `<p style="margin:0 0 12px;color:#333;font-size:14px;line-height:1.6;white-space:pre-wrap;">${escapeHtml(block)}</p>`;
  });

  return `<!doctype html>
<html><body style="margin:0;padding:0;background:#f6f4ef;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif;">
  <div style="max-width:640px;margin:0 auto;padding:32px 28px;background:#ffffff;">
    <p style="font-size:11px;letter-spacing:0.18em;text-transform:uppercase;color:#a05a3c;margin:0 0 6px;font-weight:700;">Your ${escapeHtml(documentKind)} from People.Studio</p>
    <h1 style="font-size:22px;margin:0 0 24px;color:#1a1a1a;font-weight:600;">${escapeHtml(documentName)}</h1>
    ${blocks.join("\n")}
    <hr style="border:none;border-top:1px solid #e8dfd1;margin:28px 0 18px;" />
    <p style="font-size:12px;color:#7a7268;line-height:1.6;margin:0;">
      Generated by <strong>People.Studio</strong> — <a href="https://peopl.studio" style="color:#a05a3c;text-decoration:none;">peopl.studio</a><br/>
      This is a starter draft. For a fully tailored, legally reviewed version, reply to this email or
      <a href="${BOOKING_LINK}" style="color:#a05a3c;text-decoration:none;">book a call</a>.
    </p>
  </div>
</body></html>`;
}

function renderText(documentKind: string, documentName: string, outputText: string) {
  return `${documentName}
(${documentKind})

${outputText}

— — —
Generated by People.Studio — peopl.studio
This is a starter draft. For a fully tailored, legally reviewed version, reply to this email or book a call at ${BOOKING_LINK}`;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY");
    if (!LOVABLE_API_KEY) throw new Error("LOVABLE_API_KEY is not configured");
    if (!RESEND_API_KEY) throw new Error("RESEND_API_KEY is not configured");

    const FROM_EMAIL = Deno.env.get("RESEND_FROM_EMAIL") || DEFAULT_FROM_EMAIL;

    const body = (await req.json()) as Partial<RequestBody>;

    // Validate
    const toEmail = (body.toEmail || "").trim();
    const documentKind = (body.documentKind || "").toString().slice(0, 80);
    const documentName = (body.documentName || "").toString().slice(0, 200);
    const outputText = (body.outputText || "").toString().slice(0, 200000);

    const emailValid = /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(toEmail) && toEmail.length <= 320;
    if (!emailValid) {
      return new Response(JSON.stringify({ error: "Invalid recipient email" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }
    if (!documentKind || !documentName || !outputText) {
      return new Response(JSON.stringify({ error: "Missing documentKind, documentName, or outputText" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Internal lead notification: always send to mrshow2@gmail.com (Resend sandbox limit).
    // Includes the user's email and the generated tool output for follow-up.
    const INTERNAL_RECIPIENT = "mrshow2@gmail.com";
    const subject = `[Lead] ${toEmail} — ${documentName} (${documentKind})`;

    const leadHtml = `<!doctype html>
<html><body style="margin:0;padding:0;background:#f6f4ef;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif;">
  <div style="max-width:680px;margin:0 auto;padding:32px 28px;background:#ffffff;">
    <p style="font-size:11px;letter-spacing:0.18em;text-transform:uppercase;color:#a05a3c;margin:0 0 6px;font-weight:700;">New free-tool lead</p>
    <h1 style="font-size:20px;margin:0 0 18px;color:#1a1a1a;font-weight:600;">${escapeHtml(documentName)} (${escapeHtml(documentKind)})</h1>
    <table style="width:100%;border-collapse:collapse;margin:0 0 22px;font-size:14px;color:#333;">
      <tr><td style="padding:6px 0;color:#7a7268;width:120px;">Lead email</td><td style="padding:6px 0;"><a href="mailto:${escapeHtml(toEmail)}" style="color:#a05a3c;text-decoration:none;">${escapeHtml(toEmail)}</a></td></tr>
      <tr><td style="padding:6px 0;color:#7a7268;">Document</td><td style="padding:6px 0;">${escapeHtml(documentName)}</td></tr>
      <tr><td style="padding:6px 0;color:#7a7268;">Type</td><td style="padding:6px 0;">${escapeHtml(documentKind)}</td></tr>
    </table>
    <hr style="border:none;border-top:1px solid #e8dfd1;margin:0 0 18px;" />
    <h2 style="font-size:14px;margin:0 0 12px;color:#1a1a1a;text-transform:uppercase;letter-spacing:0.1em;">Generated output</h2>
    ${renderHtml(documentKind, documentName, outputText).split("<body")[1]?.split(">").slice(1).join(">").replace(/<\/body>[\s\S]*$/, "") || `<pre style="white-space:pre-wrap;font-family:inherit;font-size:13px;color:#333;">${escapeHtml(outputText)}</pre>`}
  </div>
</body></html>`;

    const leadText = `NEW FREE-TOOL LEAD

Lead email: ${toEmail}
Document: ${documentName}
Type: ${documentKind}

--- Generated output ---

${outputText}`;

    const response = await fetch(`${GATEWAY_URL}/emails`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${LOVABLE_API_KEY}`,
        "X-Connection-Api-Key": RESEND_API_KEY,
      },
      body: JSON.stringify({
        from: `${FROM_NAME} <${FROM_EMAIL}>`,
        to: [INTERNAL_RECIPIENT],
        subject,
        html: leadHtml,
        text: leadText,
        reply_to: toEmail,
      }),
    });

    const data = await response.json().catch(() => ({}));
    if (!response.ok) {
      console.error("Resend send failed", response.status, data);
      return new Response(
        JSON.stringify({ error: "Email provider rejected the send", status: response.status, details: data }),
        { status: 502, headers: { ...corsHeaders, "Content-Type": "application/json" } },
      );
    }

    return new Response(JSON.stringify({ success: true, id: data?.id }), {
      status: 200,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Unknown error";
    console.error("send-tool-email error:", message);
    return new Response(JSON.stringify({ error: message }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
